packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: 5.9.3
  eslint: 9.39.4

minimumReleaseAge: 0

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: false
  core-js: true

minimumReleaseAgeExclude:
  - "@clerk/*"
  - "@shadcn/*"
  - "@types/*"
