packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 0

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: false
  core-js: true

minimumReleaseAgeExclude:
  - "@clerk/*"
  - "@shadcn/*"
  - "@types/*"
